version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: tungno
      MYSQL_DATABASE: mmfood
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: tungno
      DB_NAME: mmfood
      JWT_SECRET: "tungno le didim"
      ALLOWED_ORIGINS: "http://frontend:3000,http://localhost:3000,http://admin:5173,http://localhost:5173"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_BASE_URL: "http://backend:8080"
    restart: always

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
